theme: jekyll-theme-cayman
title: Holiday Hackathon
description: A fun, beginner-friendly hackathon open to all students, hosted by the Foothill CS Club.
organizer: Foothill CS Club
dates: Saturday, December 26 - Thursday, December 31
discord_invite: https://discord.gg/graRNeE
