theme: jekyll-theme-cayman
title: Holiday Hackathon
description: A fun, beginner-friendly hackathon for all students, hosted by the Foothill CS Club.
organizer: Foothill CS Club
dates: Saturday, December 26 - Wednesday, December 30
discord_invite: https://discord.gg/graRNeE
